excluded:
  - .build
  - Package.swift

line_length:
  warning: 150
  error: 200

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 20

large_tuple:
  warning: 7
  error: 9

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - fd
    - ip
    - i
    - j
    - t
    - x
    - y

opt_in_rules:
  - empty_count
  - empty_string
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - sorted_first_last
  - yoda_condition

disabled_rules:
  - todo
  - trailing_comma
  - opening_brace
